apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi